In [3]:
# Read the csv file and create pd dataframe
import pandas as pd 
df = pd.read_csv('spotify-2023.csv', encoding='latin1')
df.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6

In [5]:
# Number of songs in the dataset (rows)
print("Number of songs in the dataset: ", df.shape[0])

Number of songs in the dataset:  953

In [7]:
df_E_key = df[df['key'] == 'E']
df_E_key.head()

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
33,Anti-Hero,Taylor Swift,1,2022,10,21,9082,56,999748277,242,...,97,E,Major,64,51,63,12,0,19,5
34,TQG,"Karol G, Shakira",2,2023,2,23,4284,49,618990393,115,...,180,E,Minor,72,61,63,67,0,9,28
54,Another Love,Tom Odell,1,2012,10,15,18371,83,1813673666,250,...,123,E,Minor,45,13,54,70,0,9,4
76,Here With Me,d4vd,1,2022,7,17,3246,23,635412045,94,...,132,E,Major,58,27,48,50,0,12,3
103,Mockingbird,Eminem,1,2004,1,1,12985,61,1241559043,49,...,84,E,Minor,62,24,67,21,0,13,28

In [8]:
print("Number of songs in the dataset with key E: ", df_E_key.shape[0])

Number of songs in the dataset with key E:  62

In [11]:
# Name of the columns in df
print("Name of the columns in df: ", df.columns)

Name of the columns in df:  Index(['track_name', 'artist(s)_name', 'artist_count', 'released_year',
       'released_month', 'released_day', 'in_spotify_playlists',
       'in_spotify_charts', 'streams', 'in_apple_playlists', 'in_apple_charts',
       'in_deezer_playlists', 'in_deezer_charts', 'in_shazam_charts', 'bpm',
       'key', 'mode', 'danceability_%', 'valence_%', 'energy_%',
       'acousticness_%', 'instrumentalness_%', 'liveness_%', 'speechiness_%'],
      dtype='object')

In [14]:
#Given a column name, find the value with the most occurrences
def most_occurrences(column_name, df=df):
    return df[column_name].value_counts().idxmax()

print("Total number of songs: ", df.shape[0])
print("Most common artist: ", most_occurrences("artist(s)_name"), " with ", df["artist(s)_name"].value_counts().max(), " occurrences")
print("Most common key: ", most_occurrences("key"), " with ", df["key"].value_counts().max(), " occurrences")
print("Most common mode: ", most_occurrences("mode"), " with ", df["mode"].value_counts().max(), " occurrences")
print("Most common bmp: ", most_occurrences("bpm"), " with ", df["bpm"].value_counts().max(), " occurrences")

Total number of songs:  953
Most common artist:  Taylor Swift  with  34  occurrences
Most common key:  C#  with  120  occurrences
Most common mode:  Major  with  550  occurrences
Most common bmp:  120  with  39  occurrences